name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install, build
        run: |
          npm install
      - name: Install and configure LHCI CLI
        run: |
          npm install -g @lhci/cli@0.13.x
      - name: Run Lighthouse CI and upload report
        run: |
          lhci autorun --upload.target=lhci --upload.serverBaseUrl=https://lighthouse-server-production-8084.up.railway.app/ --upload.token=0ac98669-2c1f-4b1d-99c2-4acd8f163e45
        