name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  run-lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse tests
        run: npm run lhci --upload.target=http://localhost:64399 # Adjust port and URL as needed
