name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
      - name: npm install, build
        run: |
          npm install
          npm run build # Assuming your build script is defined in your package.json
          npm install -g serve
      - name: Install and configure LHCI CLI
        run: |
          npm install -g @lhci/cli@0.13.x
      - name: Run Lighthouse CI and upload report
        run: |
          lhci autorun --collect.startServerReadyPattern=local --collect.startServerCommand=npm run preview --collect.url=${{secrets.AUDIT_URL}} --collect.numberOfRuns=1 
          --upload.target=lhci --upload.serverBaseUrl=${{ secrets.LHCI_SERVER_URL }} --upload.token=${{ secrets.LHCI_BUILD_TOKEN }}
