name: Lighthouse CI for Netlify sites
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Choose the appropriate Node.js version
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Run Lighthouse on urls and upload data to private lhci server
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: 'https://ang-todotask.netlify.app/'
          serverBaseUrl: 'http://localhost:9001/'
          serverToken: '859bb99f-85d0-44d0-9b89-a19b0f1fddcb'
          
