name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install, build
        run: |
          npm install
      - name: Install and configure LHCI CLI
        run: |
          npm install -g @lhci/cli@0.13.x
      - name: Run Lighthouse CI and upload report
        run: |
          lhci autorun --upload.target=lhci --upload.token=859bb99f-85d0-44d0-9b89-a19b0f1fddcb --upload.serverBaseUrl=http://localhost:52009
        